### ISSUE TITLE
Color picker enhancements

### ISSUE THREAD

**Issue by RoadXY** [galadril/DomoticzForAndroid#181]
http://domoticz.com/forum/viewtopic.php?f=37&t=8884&sid=356073af40d17f17b0aea2d832d1d9ce&p=67648#p67663

by Rawkh » Sat Jan 02, 2016 2:10 am

could you make the changes from the colour wheel instantenous (like in the edit screen of domoticz itself)? The colours don't map one to one so I play around with the different options to get the colour I like. 

Pressing the color button, selecting a colur and then pressing ok becomes quite tiresome I noticed.
Maybe you can add a cancel option so that people can revert the changes if they don't like the colour they selected?

**Comment by galadril** [comment]
"could you make the changes from the colour wheel instantenous " > changed

"The colours don't map one to one " > I have problems calculating the correct hue value from the color picker.. still an issue :(

"Maybe you can add a cancel option so that people can revert the changes" > you can always dismis a dialog with the Android default (onscreen) backbutton

**Comment by RoadXY** [comment]
Close for now
