### ISSUE TITLE
[bug] cameras don't working

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#31]
I have an IP cam and a logitech webcam on my pi.    the webcam doens't work at the moment on domoticz but the Ip cam do.

this is the debug log in app:

Connection OK
- Result: [CameraInfo{idx=4, Name='Camera', Address='192.168.0.11', ImageURL='cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=#USERNAME&pwd=#PASSWORD, Port='89, Username='remb0, Password='down4free, FullURL='http://username:password@192.168.0.11:89/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=#USERNAME&pwd=#PASSWORD, Enabled=true'}, CameraInfo{idx=5, Name='Webcam', Address='192.168.0.8', ImageURL='uvccapture.cgi, Port='8080, Username=', Password=', FullURL='http://192.168.0.8:8080/uvccapture.cgi, Enabled=true'}]

**Comment by galadril** [comment]
This result shows 2 camera's and it tries to get the snapshot from the next url:
- http://username:password@192.168.0.11:89/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=#USERNAME&pwd=#PASSWORD
- http://192.168.0.8:8080/uvccapture.cgi

Which one doesn't work? (i bet the first one).
Could you debug on your own network what would be the correct working url?

It looks like the problem lies with the username password, I've added them in front of the url, but I think it should also be replaced at #USERNAME right?

**Comment by remb0** [comment]
both don't work but the uvc cam isn't connected atm.

The other one:
in edit mode i see this at snapshot url:
cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=#USERNAME&pwd=#PASSWORD

I have a: Foscam FI9821W V2 and configured as: http://domoticz.com/wiki/Camera_Setup#Foscam_FI9821W_V2

when I enter: http://username:password@192.168.0.11:89/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=#USERNAME&pwd=#PASSWORD
in the browser and replace:
username:password   and #USERNAME  and  #PASSWORD
it works.

**Comment by galadril** [comment]
Please check if it works better in 
v0.1.141

**Comment by remb0** [comment]
this issues can be closed.
