### ISSUE TITLE
Blinds not correct implemented

### ISSUE THREAD

**Issue by galadril** [galadril/DomoticzForAndroid#42]
The Blinds are not correctly implemented at this moment in the app. 

It looks like only some of the blinds work like on/off switches, some of the switches are on/off with a dimmer level, some of them are inverted on/off and the last type are Venetian Blinds.. Which have On/Off and Stop as functions.

![1](https://cloud.githubusercontent.com/assets/14561640/11372268/bd5e915c-92cc-11e5-8bec-cb7b703c7ec3.png)

![2](https://cloud.githubusercontent.com/assets/14561640/11372269/bd613a10-92cc-11e5-88ed-10ec2c08d84e.png)

![3](https://cloud.githubusercontent.com/assets/14561640/11372272/bd79dda4-92cc-11e5-8ce8-2855929ecb02.png)

![4](https://cloud.githubusercontent.com/assets/14561640/11372271/bd70c21e-92cc-11e5-8f17-79c586823453.png)

![5](https://cloud.githubusercontent.com/assets/14561640/11372266/bd5821fa-92cc-11e5-8bc5-0991b2cea7ad.png)

![6](https://cloud.githubusercontent.com/assets/14561640/11372270/bd62d3ca-92cc-11e5-9347-ad3e43da3add.png)

![7](https://cloud.githubusercontent.com/assets/14561640/11372267/bd5bb4dc-92cc-11e5-9d4e-b66a5c37b6cd.png)

We need to try to make a list of Type + Switch type combination for Dimmers and how they behave within Domoticz.. Or find the difference within the JSON between on/off, off/on or on/stop/off actions!

**Comment by galadril** [comment]
Maybe we could ask gizmocuz how Domoticz knows which logic is behind which Blind?

**Comment by RoadXY** [comment]
Done

**Comment by gizmocuz** [comment]
It is because there are many type of blinds.
The commands to be send are indeed 'On' and 'Off' and 'Stop'.
If you connect your blinds correct, you should not need (in my opinion) the blinds-inverted,
but some people had issues.
Best is to add these blinds in domoticz (can be on a virtual dummy sensor), and open the web gui in chrome.
If you open the developer console (F12) you can inspect the icon elements and see what is send.

For normal Blinds:
- Off (opens the blinds)
- On (closed the blinds)

For inverted Blinds:
- On (opens the blinds)
- Off (closed the blinds)

For blinds with percentages, you can also send a dimmer value (0-100%) (like a fibaro roller shutter)
And blinds with a stop button, you should send the 'Stop' command

Blinds with a stop button are not available for all hardware.
For example if you manually add a Blinds T6 type, and set this switch to 'blinds' then you have the stop button
You can see this in the code from LightsController.js

**Comment by galadril** [comment]
@gizmocuz 

Thanks for your reaction!

Is there a way for me to see in the JSON results if a Blind support on/off, off/on or also a stop button?
It would be easier for me if there is an indicater in the JSON.

 {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 10,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "73",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2015-11-24 15:38:07",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "testBlind",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "ELRO AB400",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Lighting 1",
         "TypeImg" : "blinds",
         "Unit" : 7,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "176"
      },

**Comment by galadril** [comment]
I think i've nailed the Blind implementation!
I've been testing lots of Blinds..

![blinds](https://cloud.githubusercontent.com/assets/14561640/11689292/9244bc8c-9e91-11e5-8048-bb0f479592e2.png)

Please check if we can close this case!
