### ISSUE TITLE
Android ware

### ISSUE THREAD

**Issue by remb0** [galadril/DomoticzForAndroid#58]
The moto360 is quite slow with starting domoticz.   the moto360 first edition displays the domoticz logo quite long before I can use it.

Is it possible to start the app with roomplan (so it would load as long as the device list).  
so users can choose the right room (ans maybe the devices would be loaded on background?)

And when choosing the right plan you have to scroll less because the bevices already filtered.

**Comment by galadril** [comment]
**"Is it possible to start the app with roomplan (so it would load as long as the device list)"**
If no switches selected on the app, the wear app shows only switches from your dashboard, so not 'every' switch.

I do think it's needed for the wear app to check the connection with the phone app, else we get questions like 'nothing is happening when i selected a switch'. Then it could be because of the bleutooth connection. 

So I think its because of the Wear bleuthooth connection if it's loading slow..

**Comment by remb0** [comment]
I have selected many switches I often use.  so a lot of scrolling :)
you are right about the speed.  But I also think it's the moto360   I will test it today also on the first gen g watch of my wife.
